#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Alicloud.Apm.Editor
{
    [InitializeOnLoad]
    internal static class PackageVersionGenerator
    {
        private const string PackageJsonAssetPath = "Assets/alicloud-apm/package.json";
        private const string OutputAssetPath =
            "Assets/alicloud-apm/Runtime/Internal/Generated/ApmVersionInfo.cs";

        static PackageVersionGenerator()
        {
            EditorApplication.delayCall += () => RefreshVersion(logOnChange: false);
        }

        internal static void RefreshVersion(bool logOnChange)
        {
            try
            {
                var version = ReadVersionFromPackage();
                if (string.IsNullOrEmpty(version))
                {
                    version = "unknown";
                }

                var content = BuildSource(version);
                var outputPath = GetFullPath(OutputAssetPath);
                if (File.Exists(outputPath) && File.ReadAllText(outputPath) == content)
                {
                    return;
                }

                var directory = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                File.WriteAllText(outputPath, content);
                AssetDatabase.ImportAsset(OutputAssetPath, ImportAssetOptions.ForceUpdate);

                if (logOnChange)
                {
                    ApmEditorLogger.Info($"Updated generated SDK version to {version}");
                }
            }
            catch (Exception ex)
            {
                ApmEditorLogger.Warning($"Failed to refresh SDK version: {ex.Message}");
            }
        }

        private static string ReadVersionFromPackage()
        {
            try
            {
                var manifestPath = GetFullPath(PackageJsonAssetPath);
                if (!File.Exists(manifestPath))
                {
                    return null;
                }

                var json = File.ReadAllText(manifestPath);
                var manifest = JsonUtility.FromJson<PackageManifest>(json);
                return manifest?.version;
            }
            catch (Exception ex)
            {
                ApmEditorLogger.Warning($"Failed to parse package.json: {ex.Message}");
                return null;
            }
        }

        private static string BuildSource(string version)
        {
            var sanitizedVersion = version.Replace("\\", "\\\\").Replace("\"", "\\\"");
            return $"// <auto-generated>\n"
                + "// This file is generated. Run the editor tooling to regenerate.\n"
                + "// </auto-generated>\n\n"
                + "namespace Alicloud.Apm\n"
                + "{\n"
                + "    internal static class ApmVersionInfo\n"
                + "    {\n"
                + $"        internal const string Version = \"{sanitizedVersion}\";\n"
                + "    }\n"
                + "}\n";
        }

        private static string GetFullPath(string assetPath)
        {
            var projectRoot = Path.GetDirectoryName(Application.dataPath) ?? string.Empty;
            return Path.GetFullPath(Path.Combine(projectRoot, assetPath));
        }

        [Serializable]
        private class PackageManifest
        {
            public string version;
        }
    }

    internal sealed class PackageVersionPreprocessor : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            PackageVersionGenerator.RefreshVersion(logOnChange: true);
        }
    }
}
#endif
