// 启用 AllocationTracker 在生产环境（注释此行可禁用）
#define ALLOCATION_TRACKER_ENABLED 1

#ifdef ALLOCATION_TRACKER_ENABLED
#define _INTERNAL_EAPMAT_ENABLED (ALLOCATION_TRACKER_ENABLED)
#else
#define _INTERNAL_EAPMAT_ENABLED DEBUG
#endif // ALLOCATION_TRACKER_ENABLED
